name:                penniless-pilgrim
version:             0.1.0.0
github:              "Deltaspace0/Penniless-Pilgrim"
license:             MIT
author:              "Deltaspace0"
maintainer:          "rgadeew@yandex.ru"
copyright:           "2022 Deltaspace0"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Deltaspace0/Penniless-Pilgrim#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- text
- monomer
- data-default
- text-show
- array

library:
  source-dirs: src

executables:
  penniless-pilgrim-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - penniless-pilgrim

tests:
  penniless-pilgrim-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - penniless-pilgrim
